# Generated by Django 4.2.1 on 2023-06-20 13:14

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_discount_price', models.PositiveIntegerField(blank=True)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('product_desc', models.TextField()),
                ('product_specif', models.TextField()),
                ('product_color', models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Pink', 'Pink'), ('Silver', 'Silver'), ('white', 'white'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('transparent', 'transparent')], max_length=20)),
                ('product_category', models.CharField(choices=[('computer', 'computer'), ('phone', 'phone'), ('keyboard', 'keyboard'), ('mouse', 'mouse'), ('earphones', 'earphones'), ('phone cover', 'phone cover'), ('computer components', 'computer components')], max_length=20)),
                ('product_pic_1', products.models.CustomResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[200, 200], upload_to='product_pics')),
                ('product_pic_2', products.models.CustomResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[200, 200], upload_to='product_pics')),
                ('product_pic_3', products.models.CustomResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[200, 200], upload_to='product_pics')),
                ('product_pic_4', products.models.CustomResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[200, 200], upload_to='product_pics')),
            ],
        ),
        migrations.DeleteModel(
            name='AddProducts',
        ),
    ]
